# 生产镜像，仅包含应用代码
# FROM ghcr.io/xinnan-tech/xiaozhi-esp32-server:server-base

# ❌ Dòng cũ (xóa đi):
# FROM xiaozhi-esp32-server:server-base-latest

# ✅ Sửa thành (thay tên user của bạn vào):
FROM ghcr.io/trinhtanphat/xiaozhi-esp32-server:server-base-vnso

COPY main/xiaozhi-server .

# 启动应用
CMD ["python", "app.py"]